version: "3.5"

networks:
  ingress:

volumes:
  traefik-cert: 


services:
  ingress:
    image: traefik:v1.7.12-alpine
    ports:
      - 80:80
      - 443:443
    deploy:
      replicas: ${TRAEFIK_REPLICAS:-1}
      placement:
        constraints:
          - node.role == manager
        preferences:
          - spread: node.id
      labels:
        - traefik.frontend.rule=Host:traefik.${DOMAIN?Variable DOMAIN not set}
        - traefik.enable=true
        - traefik.port=8080
        - traefik.tags=ingress 
        - traefik.docker.network=${STACK_NAME:-technocore}_ingress
        # Traefik service that listens to HTTP
        - traefik.redirectorservice.frontend.entryPoints=http
        - traefik.redirectorservice.frontend.redirect.entryPoint=https
        # Traefik service that listens to HTTPS
        - traefik.webservice.frontend.entryPoints=https
    logging:
      driver: "${LOGGING_DRIVER}"
      options:
        tag: "{{.Name}}"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - traefik-cert:/etc/traefik/acme/ 
    command: >
      --docker
      --docker.swarmmode
      --docker.watch
      --docker.exposedbydefault=false
      --constraints=tag==ingress
      --entrypoints='Name:http Address::80'
      --entrypoints='Name:https Address::443 TLS'
      --acme
      --acme.email=${EMAIL?Variable EMAIL not set}
      --acme.storage="/etc/traefik/acme/acme.json"
      --acme.entryPoint=https
      ${TRAEFIK_LETS_ENCRYPT_CHALLENGE:---acme.httpChallenge.entryPoint=http}
      ${TRAEFIK_ACME_CASERVER}
      --acme.onhostrule=true
      --acme.acmelogging=true
      --logLevel=INFO
      --accessLog
      --api
    networks:
      - ingress
